# Generated by Django 2.0.1 on 2018-01-09 05:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlcProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.CharField(max_length=80)),
                ('prod_nm', models.CharField(max_length=255)),
                ('prod_desc', models.TextField()),
                ('created_dt', models.DateTimeField(default=datetime.datetime.now)),
                ('sta_eff_dt', models.CharField(max_length=8)),
                ('end_eff_dt', models.CharField(max_length=8)),
                ('tot_user_qty', models.DecimalField(decimal_places=0, max_digits=5)),
                ('tot_server_qty', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SqlcProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(default=datetime.datetime.now)),
                ('project_nm', models.CharField(max_length=255)),
                ('project_desc', models.TextField()),
                ('sta_eff_dt', models.CharField(max_length=8)),
                ('end_eff_dt', models.CharField(max_length=8)),
                ('ownername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pjtmgmt.SqlcProd')),
            ],
        ),
    ]
