# Generated by Django 2.0.1 on 2018-03-15 04:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pjtmgmt.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pjtmgmt', '0005_mntgroupuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlcProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(default=datetime.datetime.now)),
                ('project_nm', models.CharField(default='프로젝트 명칭', max_length=255)),
                ('project_desc', models.TextField(default='프로젝트 설명')),
                ('sta_eff_dt', models.CharField(max_length=8)),
                ('end_eff_dt', models.CharField(max_length=8)),
                ('owner', models.ForeignKey(on_delete=models.SET(pjtmgmt.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pjtmgmt.SqlcProd')),
            ],
        ),
    ]
