# Generated by Django 2.0.1 on 2018-03-29 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pjtmgmt', '0007_auto_20180315_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mntgroup',
            name='mnt_group_desc',
            field=models.TextField(default='그룹에 대한 설명을 적어 주세요'),
        ),
        migrations.AlterField(
            model_name='mntgroup',
            name='mnt_group_nm',
            field=models.CharField(default='모니터링 그룹 명칭을 등록하세요', max_length=255),
        ),
        migrations.AlterField(
            model_name='mntserver',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pjtmgmt.SqlcProject'),
        ),
    ]
