# Generated by Django 2.0.1 on 2018-04-09 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pjtmgmt', '0008_auto_20180329_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mntgroup',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pjtmgmt.SqlcProject'),
        ),
        migrations.AlterField(
            model_name='mntgroupserver',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pjtmgmt.SqlcProject'),
        ),
    ]
