# Generated by Django 2.0.1 on 2018-04-13 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pjtmgmt', '0009_auto_20180409_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mntgroupuser',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pjtmgmt.SqlcProject'),
        ),
    ]
